/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.adhoccom.atbank;

import com.adhoccom.atbank.Main.Account;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter;

/**
 *
 * @author dermh
 */
public class Home extends javax.swing.JFrame {

    private Account account;

    /**
     * Creates new form Home
     *
     * @param account
     */
    public Home(Account account) {
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
            javax.swing.UIManager.put("Button.arc", 15);
            javax.swing.UIManager.put("Component.arc", 15);
            javax.swing.UIManager.put("ProgressBar.arc", 999);
            javax.swing.UIManager.put("TextComponent.arc", 15);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            System.err.println("Failed to initialize LaF");
        }

        this.account = account;

        initComponents();

        nameLabel.setText(this.account.getName());

        double balance = this.account.checkBalance();
        depositBalanceLabel.setText(balance + " ฿");
        withdrawBalanceLabel.setText(balance + " ฿");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBarPanel = new javax.swing.JPanel();
        appLabel = new javax.swing.JLabel();
        depositButton = new javax.swing.JButton();
        withdrawButton = new javax.swing.JButton();
        transferButton = new javax.swing.JButton();
        checkBalanceButton = new javax.swing.JButton();
        signOutButton = new javax.swing.JButton();
        greetingPanel = new javax.swing.JPanel();
        greetingLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        contentsPanel = new javax.swing.JPanel();
        depositPanel = new javax.swing.JPanel();
        depositHeaderPanel = new javax.swing.JPanel();
        depositTitleLabel = new javax.swing.JLabel();
        depositDescriptionLabel = new javax.swing.JLabel();
        depositBodyPanel = new javax.swing.JPanel();
        depositBalanceTextLabel = new javax.swing.JLabel();
        depositBalanceLabel = new javax.swing.JLabel();
        depositAmountLabel = new javax.swing.JLabel();
        depositSpinner = new javax.swing.JSpinner();
        depositFooterPanel = new javax.swing.JPanel();
        depositConfirm = new javax.swing.JButton();
        depositCancle = new javax.swing.JButton();
        withdrawPanel = new javax.swing.JPanel();
        withdrawHeaderPanel = new javax.swing.JPanel();
        withdrawTitleLabel = new javax.swing.JLabel();
        withdrawDescriptionLabel = new javax.swing.JLabel();
        withdrawBodyPanel = new javax.swing.JPanel();
        withdrawBalanceTextLabel = new javax.swing.JLabel();
        withdrawBalanceLabel = new javax.swing.JLabel();
        withdrawAmountLabel = new javax.swing.JLabel();
        withdrawSpinner = new javax.swing.JSpinner();
        withdrawFooterPanel = new javax.swing.JPanel();
        withdrawConfirmButton = new javax.swing.JButton();
        transferPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        checkBalancePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ATBank");
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Kanit", 0, 10)); // NOI18N
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/adhoccom/atbank/icons/credit-card-24.png")).getImage());

        sideBarPanel.setBackground(new java.awt.Color(102, 0, 204));

        appLabel.setFont(new java.awt.Font("Kanit", 1, 18)); // NOI18N
        appLabel.setForeground(new java.awt.Color(255, 255, 255));
        appLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/adhoccom/atbank/icons/credit-card-24.png"))); // NOI18N
        appLabel.setText("ATBank");

        depositButton.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        depositButton.setText("ฝาก");
        depositButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });

        withdrawButton.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        withdrawButton.setText("ถอน");
        withdrawButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });

        transferButton.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        transferButton.setText("โอน");
        transferButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferButtonActionPerformed(evt);
            }
        });

        checkBalanceButton.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        checkBalanceButton.setText("เช็คยอด");
        checkBalanceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkBalanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBalanceButtonActionPerformed(evt);
            }
        });

        signOutButton.setBackground(new java.awt.Color(255, 0, 0));
        signOutButton.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        signOutButton.setForeground(new java.awt.Color(255, 255, 255));
        signOutButton.setIcon(new FlatSVGIcon("com/adhoccom/atbank/icons/arrow-alt-circle-left.svg", 16, 16).setColorFilter(new ColorFilter(color -> new java.awt.Color(255, 255, 255)))
        );
        signOutButton.setText("ออกจากระบบ");
        signOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutButtonActionPerformed(evt);
            }
        });

        greetingPanel.setBackground(new java.awt.Color(102, 0, 204));
        greetingPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        greetingLabel.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        greetingLabel.setForeground(new java.awt.Color(255, 255, 255));
        greetingLabel.setText("ยินดีต้อนรับคุณ");
        greetingPanel.add(greetingLabel);

        nameLabel.setFont(new java.awt.Font("Kanit", 1, 12)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        nameLabel.setText("User");
        greetingPanel.add(nameLabel);

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(withdrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transferButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkBalanceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(appLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depositButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(greetingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(appLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(greetingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(withdrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transferButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkBalanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(signOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(sideBarPanel, java.awt.BorderLayout.LINE_START);

        contentsPanel.setLayout(new java.awt.CardLayout());

        depositPanel.setBackground(new java.awt.Color(241, 243, 249));
        depositPanel.setLayout(new java.awt.BorderLayout());

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5);
        flowLayout1.setAlignOnBaseline(true);
        depositHeaderPanel.setLayout(flowLayout1);

        depositTitleLabel.setFont(new java.awt.Font("Kanit", 1, 24)); // NOI18N
        depositTitleLabel.setForeground(new java.awt.Color(102, 0, 204));
        depositTitleLabel.setText("| ฝากเงิน ");
        depositHeaderPanel.add(depositTitleLabel);

        depositDescriptionLabel.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        depositDescriptionLabel.setText("ฝากเงินให้เป็นนิสัย อดออมไว้ใช้ในอนาคต");
        depositHeaderPanel.add(depositDescriptionLabel);

        depositPanel.add(depositHeaderPanel, java.awt.BorderLayout.PAGE_START);

        depositBalanceTextLabel.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        depositBalanceTextLabel.setText("ยอดเงินคงเหลือ");

        depositBalanceLabel.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        depositBalanceLabel.setText("0 ฿");

        depositAmountLabel.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        depositAmountLabel.setLabelFor(depositSpinner);
        depositAmountLabel.setText("จำนวนเงิน");

        depositSpinner.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        depositSpinner.setModel(new javax.swing.SpinnerNumberModel(100.0d, 100.0d, null, 100.0d));
        depositSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(depositSpinner, "000"));

        javax.swing.GroupLayout depositBodyPanelLayout = new javax.swing.GroupLayout(depositBodyPanel);
        depositBodyPanel.setLayout(depositBodyPanelLayout);
        depositBodyPanelLayout.setHorizontalGroup(
            depositBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositBodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(depositBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(depositBalanceTextLabel)
                    .addComponent(depositBalanceLabel)
                    .addComponent(depositAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(depositSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(432, 432, 432))
        );
        depositBodyPanelLayout.setVerticalGroup(
            depositBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositBodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(depositBalanceTextLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositBalanceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(depositAmountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        depositPanel.add(depositBodyPanel, java.awt.BorderLayout.CENTER);

        depositConfirm.setBackground(new java.awt.Color(102, 0, 204));
        depositConfirm.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        depositConfirm.setForeground(new java.awt.Color(255, 255, 255));
        depositConfirm.setText("ฝาก");
        depositConfirm.setMargin(new java.awt.Insets(10, 20, 10, 20));
        depositConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositConfirmActionPerformed(evt);
            }
        });
        depositFooterPanel.add(depositConfirm);

        depositCancle.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        depositCancle.setText("ยกเลิก");
        depositCancle.setMargin(new java.awt.Insets(10, 20, 10, 20));
        depositCancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositCancleActionPerformed(evt);
            }
        });
        depositFooterPanel.add(depositCancle);

        depositPanel.add(depositFooterPanel, java.awt.BorderLayout.PAGE_END);

        contentsPanel.add(depositPanel, "deposit");

        withdrawPanel.setBackground(new java.awt.Color(241, 243, 249));
        withdrawPanel.setLayout(new java.awt.BorderLayout());

        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5);
        flowLayout2.setAlignOnBaseline(true);
        withdrawHeaderPanel.setLayout(flowLayout2);

        withdrawTitleLabel.setFont(new java.awt.Font("Kanit", 1, 24)); // NOI18N
        withdrawTitleLabel.setForeground(new java.awt.Color(102, 0, 204));
        withdrawTitleLabel.setText("| ถอน");
        withdrawHeaderPanel.add(withdrawTitleLabel);

        withdrawDescriptionLabel.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        withdrawDescriptionLabel.setText("ใช้จ่ายอย่างประหยัด");
        withdrawHeaderPanel.add(withdrawDescriptionLabel);

        withdrawPanel.add(withdrawHeaderPanel, java.awt.BorderLayout.PAGE_START);

        withdrawBalanceTextLabel.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        withdrawBalanceTextLabel.setText("ยอดเงินคงเหลือ");

        withdrawBalanceLabel.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        withdrawBalanceLabel.setText("0 ฿");

        withdrawAmountLabel.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        withdrawAmountLabel.setText("จำนวนเงิน");

        withdrawSpinner.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        withdrawSpinner.setModel(new javax.swing.SpinnerNumberModel(100.0d, 100.0d, null, 100.0d));
        withdrawSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(withdrawSpinner, "000"));

        javax.swing.GroupLayout withdrawBodyPanelLayout = new javax.swing.GroupLayout(withdrawBodyPanel);
        withdrawBodyPanel.setLayout(withdrawBodyPanelLayout);
        withdrawBodyPanelLayout.setHorizontalGroup(
            withdrawBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawBodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(withdrawBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(withdrawSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(withdrawBalanceTextLabel)
                    .addComponent(withdrawBalanceLabel)
                    .addComponent(withdrawAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(432, 432, 432))
        );
        withdrawBodyPanelLayout.setVerticalGroup(
            withdrawBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawBodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(withdrawBalanceTextLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(withdrawBalanceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(withdrawAmountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(withdrawSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
        );

        withdrawPanel.add(withdrawBodyPanel, java.awt.BorderLayout.CENTER);

        withdrawConfirmButton.setBackground(new java.awt.Color(102, 0, 204));
        withdrawConfirmButton.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        withdrawConfirmButton.setForeground(new java.awt.Color(255, 255, 255));
        withdrawConfirmButton.setText("ถอน");
        withdrawConfirmButton.setMargin(new java.awt.Insets(10, 20, 10, 20));
        withdrawConfirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawConfirmButtonActionPerformed(evt);
            }
        });
        withdrawFooterPanel.add(withdrawConfirmButton);

        withdrawPanel.add(withdrawFooterPanel, java.awt.BorderLayout.PAGE_END);

        contentsPanel.add(withdrawPanel, "withdraw");

        transferPanel.setBackground(new java.awt.Color(241, 243, 249));

        jLabel3.setFont(new java.awt.Font("Kanit", 1, 24)); // NOI18N
        jLabel3.setText("| โอน");

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        jLabel1.setText("เลขบัญชี");

        jFormattedTextField1.setText("jFormattedTextField1");
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        jLabel5.setText("จำนวนเงิน");

        jFormattedTextField2.setText("jFormattedTextField2");
        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 0, 51));
        jButton1.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ยกเลิก");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 204, 0));
        jButton2.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("ยืนยัน");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFormattedTextField2)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout transferPanelLayout = new javax.swing.GroupLayout(transferPanel);
        transferPanel.setLayout(transferPanelLayout);
        transferPanelLayout.setHorizontalGroup(
            transferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transferPanelLayout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        transferPanelLayout.setVerticalGroup(
            transferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(44, 44, 44)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        contentsPanel.add(transferPanel, "transfer");

        checkBalancePanel.setBackground(new java.awt.Color(241, 243, 249));

        jLabel4.setFont(new java.awt.Font("Kanit", 1, 24)); // NOI18N
        jLabel4.setText("| เช็คยอด");

        javax.swing.GroupLayout checkBalancePanelLayout = new javax.swing.GroupLayout(checkBalancePanel);
        checkBalancePanel.setLayout(checkBalancePanelLayout);
        checkBalancePanelLayout.setHorizontalGroup(
            checkBalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkBalancePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addContainerGap(482, Short.MAX_VALUE))
        );
        checkBalancePanelLayout.setVerticalGroup(
            checkBalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkBalancePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addContainerGap(451, Short.MAX_VALUE))
        );

        contentsPanel.add(checkBalancePanel, "checkBalance");

        getContentPane().add(contentsPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout card = (java.awt.CardLayout) contentsPanel.getLayout();
        card.show(contentsPanel, "withdraw");
    }//GEN-LAST:event_withdrawButtonActionPerformed

    private void transferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferButtonActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout card = (java.awt.CardLayout) contentsPanel.getLayout();
        card.show(contentsPanel, "transfer");
    }//GEN-LAST:event_transferButtonActionPerformed

    private void checkBalanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBalanceButtonActionPerformed

    }//GEN-LAST:event_checkBalanceButtonActionPerformed

    private void signOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Authentication().setVisible(true);
    }//GEN-LAST:event_signOutButtonActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout card = (java.awt.CardLayout) contentsPanel.getLayout();
        card.show(contentsPanel, "deposit");
    }//GEN-LAST:event_depositButtonActionPerformed

    private void withdrawConfirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawConfirmButtonActionPerformed
        String amountText = withdrawSpinner.getValue().toString();

        try {
            double amount = Double.parseDouble(amountText);
            double currentBalance = account.checkBalance();

            if (amount <= 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "The amount must be more than 0");
            } else if (amount > currentBalance) {
                javax.swing.JOptionPane.showMessageDialog(this, "The remaining balance is not enough.");
            } else {
                account.withdraw(amount);
                withdrawBalanceLabel.setText(account.checkBalance() + " ฿");

                javax.swing.JOptionPane.showMessageDialog(this, "Successful withdrawal");
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Please enter the correct amount.");
        }
    }//GEN-LAST:event_withdrawConfirmButtonActionPerformed

    private void depositConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositConfirmActionPerformed
        javax.swing.JOptionPane.showConfirmDialog(this, "ยืนยันจำนวนเงินที่ต้องการฝาก" + depositSpinner.getValue().toString());
    }//GEN-LAST:event_depositConfirmActionPerformed

    private void depositCancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositCancleActionPerformed
        depositSpinner.setValue(100);
    }//GEN-LAST:event_depositCancleActionPerformed

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        String accountNumber = jFormattedTextField1.getText().trim();
    
    // Check if the account number matches a specific format (e.g., only digits, 10 characters)
    if (accountNumber.matches("\\d{10}")) {
        // Valid account number, process the input
        System.out.println("Valid account number: " + accountNumber);
        // You can add further code here to handle the account number (e.g., save to a database)
    } else {
        // Invalid account number, show an error message
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Invalid account number. Please enter a 10-digit number.", 
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
     // Get the text from the formatted field and trim any spaces
    String amountText = jFormattedTextField2.getText().trim();

    try {
        // Convert the string to a number (double) to represent the monetary value
        double amount = Double.parseDouble(amountText);
        
        // Check if the amount is greater than 0 (valid amount)
        if (amount > 0) {
            // Process the valid amount
            System.out.println("Valid amount: " + amount);
            // You can add further code here to handle the amount (e.g., save to a database)
        } else {
            // Show an error message for negative or zero amounts
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Amount must be greater than zero.", 
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        // Show an error message if the input is not a valid number
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Invalid amount. Please enter a valid number.", 
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         // สมมติว่ามีฟิลด์ข้อมูลที่ต้องยืนยัน เช่น หมายเลขบัญชีและจำนวนเงิน
    String accountNumber = jFormattedTextField1.getText().trim();
    String amountText = jFormattedTextField2.getText().trim();

    // ตรวจสอบข้อมูลในฟิลด์ หมายเลขบัญชี
    if (!accountNumber.matches("\\d{10}")) {
        // แสดงข้อผิดพลาดหากหมายเลขบัญชีไม่ถูกต้อง (ต้องเป็นตัวเลข 10 หลัก)
        javax.swing.JOptionPane.showMessageDialog(this, 
            "หมายเลขบัญชีไม่ถูกต้อง. กรุณาใส่หมายเลขบัญชี 10 หลัก.", 
            "ข้อผิดพลาด", javax.swing.JOptionPane.ERROR_MESSAGE);
        return; // หยุดการทำงานหากข้อมูลไม่ถูกต้อง
    }

    try {
        // แปลงจำนวนเงินจากข้อความเป็น double
        double amount = Double.parseDouble(amountText);

        // ตรวจสอบว่าจำนวนเงินต้องมากกว่า 0
        if (amount <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "กรุณากรอกจำนวนเงินที่มากกว่า 0.", 
                "ข้อผิดพลาด", javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // หยุดการทำงานหากข้อมูลไม่ถูกต้อง
        }

        // ถ้าทุกอย่างถูกต้อง แสดงข้อความยืนยัน
        javax.swing.JOptionPane.showMessageDialog(this, 
            "ยืนยันข้อมูลเรียบร้อย!\n\nหมายเลขบัญชี: " + accountNumber + "\nจำนวนเงิน: " + amount,
            "ยืนยันสำเร็จ", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        // เพิ่มโค้ดอื่น ๆ สำหรับการประมวลผลข้อมูลที่ยืนยันแล้ว เช่น การบันทึกลงฐานข้อมูล
        System.out.println("ข้อมูลที่ยืนยัน: หมายเลขบัญชี " + accountNumber + ", จำนวนเงิน " + amount);

    } catch (NumberFormatException e) {
        // แสดงข้อผิดพลาดหากจำนวนเงินไม่ถูกต้อง (ไม่ใช่ตัวเลข)
        javax.swing.JOptionPane.showMessageDialog(this, 
            "กรุณากรอกจำนวนเงินที่ถูกต้อง.", 
            "ข้อผิดพลาด", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       // แสดงการยืนยันการยกเลิกให้กับผู้ใช้
    int response = javax.swing.JOptionPane.showConfirmDialog(this, 
        "คุณต้องการยกเลิกการทำงานหรือไม่?", 
        "ยืนยันการยกเลิก", 
        javax.swing.JOptionPane.YES_NO_OPTION);

    // หากผู้ใช้เลือก 'ใช่' (YES)
    if (response == javax.swing.JOptionPane.YES_OPTION) {
        // ปิดฟอร์มหรือทำการยกเลิกการทำงาน
        System.out.println("การทำงานถูกยกเลิก");
        this.dispose();  // ใช้ในการปิดฟอร์มปัจจุบัน
    } else {
        // หากผู้ใช้เลือก 'ไม่' (NO) ให้ทำงานต่อไป
        System.out.println("การทำงานยังดำเนินการต่อ");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appLabel;
    private javax.swing.JButton checkBalanceButton;
    private javax.swing.JPanel checkBalancePanel;
    private javax.swing.JPanel contentsPanel;
    private javax.swing.JLabel depositAmountLabel;
    private javax.swing.JLabel depositBalanceLabel;
    private javax.swing.JLabel depositBalanceTextLabel;
    private javax.swing.JPanel depositBodyPanel;
    private javax.swing.JButton depositButton;
    private javax.swing.JButton depositCancle;
    private javax.swing.JButton depositConfirm;
    private javax.swing.JLabel depositDescriptionLabel;
    private javax.swing.JPanel depositFooterPanel;
    private javax.swing.JPanel depositHeaderPanel;
    private javax.swing.JPanel depositPanel;
    private javax.swing.JSpinner depositSpinner;
    private javax.swing.JLabel depositTitleLabel;
    private javax.swing.JLabel greetingLabel;
    private javax.swing.JPanel greetingPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JButton signOutButton;
    private javax.swing.JButton transferButton;
    private javax.swing.JPanel transferPanel;
    private javax.swing.JLabel withdrawAmountLabel;
    private javax.swing.JLabel withdrawBalanceLabel;
    private javax.swing.JLabel withdrawBalanceTextLabel;
    private javax.swing.JPanel withdrawBodyPanel;
    private javax.swing.JButton withdrawButton;
    private javax.swing.JButton withdrawConfirmButton;
    private javax.swing.JLabel withdrawDescriptionLabel;
    private javax.swing.JPanel withdrawFooterPanel;
    private javax.swing.JPanel withdrawHeaderPanel;
    private javax.swing.JPanel withdrawPanel;
    private javax.swing.JSpinner withdrawSpinner;
    private javax.swing.JLabel withdrawTitleLabel;
    // End of variables declaration//GEN-END:variables
}

