/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.adhoccom.atbank;

import com.adhoccom.atbank.Main.Account;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import com.formdev.flatlaf.extras.FlatSVGIcon.ColorFilter;
import javax.swing.JOptionPane;


/**
 *
 * @author dermh
 */
public class Home extends javax.swing.JFrame {

    private Account account;

    /**
     * Creates new form Home
     *
     * @param account
     */
    public Home(Account account) {
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatLightLaf());
            javax.swing.UIManager.put("Button.arc", 15);
            javax.swing.UIManager.put("Component.arc", 15);
            javax.swing.UIManager.put("ProgressBar.arc", 999);
            javax.swing.UIManager.put("TextComponent.arc", 15);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            System.err.println("Failed to initialize LaF");
        }

        this.account = account;

        initComponents();

        nameLabel.setText(account.getName());
        
        double balance = account.checkBalance();
        checkBalance.setText(balance + " ฿");
    
        java.awt.CardLayout card = (java.awt.CardLayout) contentsPanel.getLayout();
        card.show(contentsPanel, "checkBalance");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBarPanel = new javax.swing.JPanel();
        appLabel = new javax.swing.JLabel();
        depositButton = new javax.swing.JButton();
        withdrawButton = new javax.swing.JButton();
        transferButton = new javax.swing.JButton();
        checkBalanceButton = new javax.swing.JButton();
        signOutButton = new javax.swing.JButton();
        greetingPanel = new javax.swing.JPanel();
        greetingLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        contentsPanel = new javax.swing.JPanel();
        depositPanel = new javax.swing.JPanel();
        depositHeaderPanel = new javax.swing.JPanel();
        depositTitleLabel = new javax.swing.JLabel();
        depositDescriptionLabel = new javax.swing.JLabel();
        depositBodyPanel = new javax.swing.JPanel();
        depositAmountLabel = new javax.swing.JLabel();
        depositSpinner = new javax.swing.JSpinner();
        depositActionsPanel = new javax.swing.JPanel();
        depositConfirm = new javax.swing.JButton();
        depositCancle = new javax.swing.JButton();
        withdrawPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        checkBalance = new javax.swing.JLabel();
        transferPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        checkBalancePanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ATBank");
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Kanit", 0, 10)); // NOI18N
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/com/adhoccom/atbank/icons/credit-card-24.png")).getImage());

        sideBarPanel.setBackground(new java.awt.Color(102, 0, 204));

        appLabel.setFont(new java.awt.Font("Kanit", 1, 18)); // NOI18N
        appLabel.setForeground(new java.awt.Color(255, 255, 255));
        appLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/adhoccom/atbank/icons/credit-card-24.png"))); // NOI18N
        appLabel.setText("ATBank");

        depositButton.setText("ฝาก");
        depositButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        depositButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositButtonActionPerformed(evt);
            }
        });

        withdrawButton.setText("ถอน");
        withdrawButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        withdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawButtonActionPerformed(evt);
            }
        });

        transferButton.setText("โอน");
        transferButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transferButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferButtonActionPerformed(evt);
            }
        });

        checkBalanceButton.setText("เช็คยอด");
        checkBalanceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkBalanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBalanceButtonActionPerformed(evt);
            }
        });

        signOutButton.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        signOutButton.setForeground(new java.awt.Color(255, 153, 0));
        signOutButton.setIcon(new FlatSVGIcon("com/adhoccom/atbank/icons/arrow-alt-circle-left.svg", 16, 16).setColorFilter(new ColorFilter(color -> new java.awt.Color(255, 153, 0)))
        );
        signOutButton.setText("ออกจากระบบ");
        signOutButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        signOutButton.setContentAreaFilled(false);
        signOutButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signOutButtonActionPerformed(evt);
            }
        });

        greetingPanel.setBackground(new java.awt.Color(102, 0, 204));
        greetingPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        greetingLabel.setForeground(new java.awt.Color(255, 255, 255));
        greetingLabel.setText("ยินดีต้อนรับคุณ");
        greetingPanel.add(greetingLabel);

        nameLabel.setFont(new java.awt.Font("Kanit", 1, 12)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(255, 255, 255));
        greetingPanel.add(nameLabel);

        javax.swing.GroupLayout sideBarPanelLayout = new javax.swing.GroupLayout(sideBarPanel);
        sideBarPanel.setLayout(sideBarPanelLayout);
        sideBarPanelLayout.setHorizontalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(signOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(withdrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(transferButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkBalanceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(appLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depositButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(greetingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sideBarPanelLayout.setVerticalGroup(
            sideBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(appLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(greetingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(withdrawButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transferButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkBalanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                .addComponent(signOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(sideBarPanel, java.awt.BorderLayout.LINE_START);

        contentsPanel.setLayout(new java.awt.CardLayout());

        depositPanel.setBackground(new java.awt.Color(241, 243, 249));
        depositPanel.setLayout(new java.awt.BorderLayout());

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5);
        flowLayout1.setAlignOnBaseline(true);
        depositHeaderPanel.setLayout(flowLayout1);

        depositTitleLabel.setFont(new java.awt.Font("Kanit", 1, 24)); // NOI18N
        depositTitleLabel.setForeground(new java.awt.Color(102, 0, 204));
        depositTitleLabel.setText("| ฝากเงิน ");
        depositHeaderPanel.add(depositTitleLabel);

        depositDescriptionLabel.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        depositDescriptionLabel.setText("ฝากเงินให้เป็นนิสัย อดออมไว้ใช้ในอนาคต");
        depositHeaderPanel.add(depositDescriptionLabel);

        depositPanel.add(depositHeaderPanel, java.awt.BorderLayout.PAGE_START);

        depositAmountLabel.setFont(new java.awt.Font("Kanit", 0, 14)); // NOI18N
        depositAmountLabel.setLabelFor(depositSpinner);
        depositAmountLabel.setText("จำนวนเงิน");

        depositSpinner.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        depositSpinner.setModel(new javax.swing.SpinnerNumberModel(100.0d, 100.0d, null, 100.0d));
        depositSpinner.setEditor(new javax.swing.JSpinner.NumberEditor(depositSpinner, "000"));

        javax.swing.GroupLayout depositBodyPanelLayout = new javax.swing.GroupLayout(depositBodyPanel);
        depositBodyPanel.setLayout(depositBodyPanelLayout);
        depositBodyPanelLayout.setHorizontalGroup(
            depositBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositBodyPanelLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addGroup(depositBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(depositAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(depositSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        depositBodyPanelLayout.setVerticalGroup(
            depositBodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositBodyPanelLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(depositAmountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );

        depositPanel.add(depositBodyPanel, java.awt.BorderLayout.CENTER);

        depositConfirm.setBackground(new java.awt.Color(102, 0, 204));
        depositConfirm.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        depositConfirm.setForeground(new java.awt.Color(255, 255, 255));
        depositConfirm.setText("ยืนยัน");
        depositConfirm.setMargin(new java.awt.Insets(10, 20, 10, 20));
        depositConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositConfirmActionPerformed(evt);
            }
        });
        depositActionsPanel.add(depositConfirm);

        depositCancle.setFont(new java.awt.Font("Kanit", 0, 12)); // NOI18N
        depositCancle.setText("ยกเลิก");
        depositCancle.setMargin(new java.awt.Insets(10, 20, 10, 20));
        depositCancle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositCancleActionPerformed(evt);
            }
        });
        depositActionsPanel.add(depositCancle);

        depositPanel.add(depositActionsPanel, java.awt.BorderLayout.PAGE_END);

        contentsPanel.add(depositPanel, "deposit");

        withdrawPanel.setBackground(new java.awt.Color(241, 243, 249));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jLabel2.setText("| ถอน");

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jLabel5.setText("| ระบุจำนวนเงิน");

        jButton1.setText("ถอน");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N
        jLabel6.setText("| ยอดเงินคงเหลือ");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        checkBalance.setFont(new java.awt.Font("Leelawadee UI", 0, 24)); // NOI18N

        javax.swing.GroupLayout withdrawPanelLayout = new javax.swing.GroupLayout(withdrawPanel);
        withdrawPanel.setLayout(withdrawPanelLayout);
        withdrawPanelLayout.setHorizontalGroup(
            withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawPanelLayout.createSequentialGroup()
                .addGroup(withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(withdrawPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addGroup(withdrawPanelLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkBalance)))))
                    .addGroup(withdrawPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(380, Short.MAX_VALUE))
        );
        withdrawPanelLayout.setVerticalGroup(
            withdrawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkBalance)
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(344, Short.MAX_VALUE))
        );

        contentsPanel.add(withdrawPanel, "withdraw");

        transferPanel.setBackground(new java.awt.Color(241, 243, 249));

        jLabel3.setFont(new java.awt.Font("Kanit", 1, 24)); // NOI18N
        jLabel3.setText("| โอน");

        javax.swing.GroupLayout transferPanelLayout = new javax.swing.GroupLayout(transferPanel);
        transferPanel.setLayout(transferPanelLayout);
        transferPanelLayout.setHorizontalGroup(
            transferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addContainerGap(509, Short.MAX_VALUE))
        );
        transferPanelLayout.setVerticalGroup(
            transferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addContainerGap(565, Short.MAX_VALUE))
        );

        contentsPanel.add(transferPanel, "transfer");

        checkBalancePanel.setBackground(new java.awt.Color(241, 243, 249));

        jLabel4.setFont(new java.awt.Font("Kanit", 1, 24)); // NOI18N
        jLabel4.setText("| เช็คยอด");

        javax.swing.GroupLayout checkBalancePanelLayout = new javax.swing.GroupLayout(checkBalancePanel);
        checkBalancePanel.setLayout(checkBalancePanelLayout);
        checkBalancePanelLayout.setHorizontalGroup(
            checkBalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkBalancePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addContainerGap(435, Short.MAX_VALUE))
        );
        checkBalancePanelLayout.setVerticalGroup(
            checkBalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkBalancePanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addContainerGap(565, Short.MAX_VALUE))
        );

        contentsPanel.add(checkBalancePanel, "checkBalance");

        getContentPane().add(contentsPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawButtonActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout card = (java.awt.CardLayout) contentsPanel.getLayout();
        card.show(contentsPanel, "withdraw");
    }//GEN-LAST:event_withdrawButtonActionPerformed

    private void transferButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferButtonActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout card = (java.awt.CardLayout) contentsPanel.getLayout();
        card.show(contentsPanel, "transfer");
    }//GEN-LAST:event_transferButtonActionPerformed

    private void checkBalanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBalanceButtonActionPerformed

    }//GEN-LAST:event_checkBalanceButtonActionPerformed

    private void signOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signOutButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Authentication().setVisible(true);
    }//GEN-LAST:event_signOutButtonActionPerformed

    private void depositButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositButtonActionPerformed
        // TODO add your handling code here:
        java.awt.CardLayout card = (java.awt.CardLayout) contentsPanel.getLayout();
        card.show(contentsPanel, "deposit");
    }//GEN-LAST:event_depositButtonActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed

    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String amountText = jTextField3.getText();

    try {
        double amount = Double.parseDouble(amountText);

        double currentBalance = account.checkBalance();
        if (amount <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "The amount must be more than 0");
        } else if (amount > currentBalance) {
            javax.swing.JOptionPane.showMessageDialog(this, "The remaining balance is not enough.");
        } else {
            account.withdraw(amount);

            checkBalance.setText(account.checkBalance() + " ฿");

            javax.swing.JOptionPane.showMessageDialog(this, "Successful withdrawal");
        }
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Please enter the correct amount.");
    }
    }//GEN-LAST:event_jButton1ActionPerformed
  
    private void depositConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositConfirmActionPerformed
        JOptionPane.showConfirmDialog(this, "ยืนยันจำนวนเงินที่ต้องการฝาก" +  depositSpinner.getValue());
    }//GEN-LAST:event_depositConfirmActionPerformed

    private void depositCancleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositCancleActionPerformed
        depositSpinner.setValue(100);
    }//GEN-LAST:event_depositCancleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appLabel;
    private javax.swing.JLabel checkBalance;
    private javax.swing.JButton checkBalanceButton;
    private javax.swing.JPanel checkBalancePanel;
    private javax.swing.JPanel contentsPanel;
    private javax.swing.JPanel depositActionsPanel;
    private javax.swing.JLabel depositAmountLabel;
    private javax.swing.JPanel depositBodyPanel;
    private javax.swing.JButton depositButton;
    private javax.swing.JButton depositCancle;
    private javax.swing.JButton depositConfirm;
    private javax.swing.JLabel depositDescriptionLabel;
    private javax.swing.JPanel depositHeaderPanel;
    private javax.swing.JPanel depositPanel;
    private javax.swing.JSpinner depositSpinner;
    private javax.swing.JLabel depositTitleLabel;
    private javax.swing.JLabel greetingLabel;
    private javax.swing.JPanel greetingPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel sideBarPanel;
    private javax.swing.JButton signOutButton;
    private javax.swing.JButton transferButton;
    private javax.swing.JPanel transferPanel;
    private javax.swing.JButton withdrawButton;
    private javax.swing.JPanel withdrawPanel;
    // End of variables declaration//GEN-END:variables
}
